swagger: "2.0"
info:
  description: "Service definition for Centralia web services"
  version: "1.0.0"
  title: "Swagger Centralia"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "centralia.swagger.io"
basePath: "/"
tags:
- name: "Catalogo"
  description: "Catalogo de productos"
- name: "Pedidos"
  description: "Operaciones de pedidos"
schemes:
- "https"
- "http"
paths:
  /catalog/user/{providerId}:
    get:
      tags:
      - "Catalogo"
      summary: "Obtiene el catalogo de productos por proveedor"
      description: ""
      operationId: "getCatalog"
      produces:
      - "application/json"
      parameters:
      - name: "providerId"
        in: "path"
        description: "ID del proveedor"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Catalog"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Catalog not found"
  /categories/user/{providerId}:
    get:
      tags:
      - "Catalogo"
      summary: "Obtiene las categorias de los productos por proveedor"
      description: ""
      operationId: "getCategories"
      produces:
      - "application/json"
      parameters:
      - name: "providerId"
        in: "path"
        description: "ID del proveedor"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Categories"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Catalog not found"
  /orders/user/{vendorId}:
    post:
      tags:
      - "Pedidos"
      summary: "Guarda el pedido realizado por un cliente"
      description: ""
      operationId: "postOrder"
      produces:
      - "application/json"
      parameters:
      - name: "vendorId"
        in: "path"
        description: "ID del vendedor"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Order object that needs to be added to the order_list and order"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
    get:
      tags:
      - "Pedidos"
      summary: "Obtiene los pedidos relacionados al id del vendedor"
      description: ""
      operationId: "getOrder"
      produces:
      - "application/json"
      parameters:
      - name: "vendorId"
        in: "path"
        description: "ID del vendedor"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
definitions:
  Catalog:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "ID de producto"
      category:
          type: "string"
          description: "ID de Categoria del producto"
      sku:
        type: "string"
        description: "Identificador Unico del producto en el inventario del proveedor"
      description: 
        type: "string"
        description: "Descripcion del producto"
      price: 
        type: "number"
        format: "float"
      image: 
        type: string
        format: byte 
    xml:
      name: "Catalog"
  Categories:
    type: "object"
    properties:
      category_id: 
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "Nombre de categoria del producto"
  Order:
    type: "object"
    properties:
      id:  
        type: "integer"
        format: "int64"
        description: "ID de el pedido"
      date: 
        type: string
        format: date-time
      status: 
        type: "integer"
        format: "int64"
        description: "Estatus de el pedido"
      total: 
        type: "number"
        format: "float"
        description: "Total al que asciende el pedido"
      client_name: 
        type: "string"
        description: "Nombre del cliente/negocio que realiza el pedido"
      client_id: 
        type: "integer"
        format: "int64"
        description: "ID del cliente/negocio que realiza el pedido"
      client_address: 
        type: "string"
        description: "Dirección del cliente/negocio que realiza el pedido"
      vendor_id:
        type: "integer"
        format: "int64"
        description: "ID del vendedor encargado del cliente/negocio que realiza el pedido"
      order_list:
        type: "array"
        description: "Lista de productos que conforman del pedido"
        items: 
          $ref: "#/definitions/OrderList"
  OrderList:
    type: "object"
    properties:
      id: 
        type: "integer"
        format: "int64"
        description: "Id del producto"
      sku:
        type: "string"
        description: "Identificador Unico del producto en el inventario del proveedor"
      description: 
        type: "string"
        description: "Descripcion del producto"
      quantity: 
        type: "integer"
        format: "int64"
        description: "Cantidad de unidades requeridas de el producto"
  OrderResponse:
        type: "array"
        description: "Lista de pedidos correspondientes al vendedor"
        items: 
          $ref: "#/definitions/Order"
