swagger: "2.0"
info:
    description: "Service definition for Centralia web services"
    version: "1.0.0"
    title: "Swagger Centralia"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "centralia.swagger.io"
basePath: "/"
tags:
    - name: "Usuario"
      description: "Operaciones de usuario"
    - name: "Proveedores"
      description: "Operaciones de proveedores"
    - name: "Catalogo"
      description: "Operaciones de productos"
    - name: "Pedidos"
      description: "Operaciones de pedidos"
schemes:
    - "https"
    - "http"
paths:
    /user/users/{userId}:
         get:
            tags:
                - "Usuario"
            summary: "Obtiene el usuario"
            description: ""
            operationId: "getUser"
            produces:
                - "application/json"
            parameters:
                - name: "userId"
                  in: "path"
                  description: "ID del usuario"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/UserResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "User not found"
    /provider/providers:
        get:
            tags:
                - "Proveedores"
            summary: "Obtiene la lista de proveedores"
            description: ""
            operationId: "getProviders"
            produces:
                - "application/json"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/ProvidersResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Providers not found"
    /catalog/user/{providerId}:
        get:
            tags:
                - "Catalogo"
            summary: "Obtiene el catalogo de productos por proveedor"
            description: ""
            operationId: "getCatalog"
            produces:
                - "application/json"
            parameters:
                - name: "providerId"
                  in: "path"
                  description: "ID del proveedor"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/CatalogResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Catalog not found"
    /categories/user/{providerId}:
        get:
            tags:
                - "Catalogo"
            summary: "Obtiene las categorias de los productos por proveedor"
            description: ""
            operationId: "getCategories"
            produces:
                - "application/json"
            parameters:
                - name: "providerId"
                  in: "path"
                  description: "ID del proveedor"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/CategoriesResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Catalog not found"
    /orders/user/{vendorId}:
        post:
            tags:
                - "Pedidos"
            summary: "Guarda el pedido realizado por un cliente"
            description: ""
            operationId: "postOrder"
            produces:
                - "application/json"
            parameters:
                - name: "vendorId"
                  in: "path"
                  description: "ID del vendedor"
                  required: true
                  type: "integer"
                  format: "int64"
                - in: "body"
                  name: "body"
                  description: "Objeto que contiene la informacion y la lista de productos de la orden"
                  required: true
                  schema:
                      $ref: "#/definitions/OrderRequest"
            responses:
                "200":
                    description: "successful operation"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Order not found"
        get:
            tags:
                - "Pedidos"
            summary: "Obtiene los pedidos relacionados al id del vendedor"
            description: ""
            operationId: "getOrder"
            produces:
                - "application/json"
            parameters:
                - name: "vendorId"
                  in: "path"
                  description: "ID del vendedor"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/OrderResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Order not found"
    /orders/order/{orderId}:
        get:
            tags:
                - "Pedidos"
            summary: "Obtiene la lista de productos de la orden"
            description: ""
            operationId: "getOrderList"
            produces:
                - "application/json"
            parameters:
                - name: "orderId"
                  in: "path"
                  description: "ID de la Orden"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        $ref: "#/definitions/OrderListResponse"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Order not found"
    /orders/status/{orderId}:
        post:
            tags:
                - "Pedidos"
            summary: "Cambia el Estatus del pedido"
            description: ""
            operationId: "postOrderStatus"
            produces:
                - "application/json"
            parameters:
                - name: "orderId"
                  in: "path"
                  description: "ID de la orden"
                  required: true
                  type: "integer"
                  format: "int64"
                - in: "body"
                  name: "body"
                  description: "Objeto que contiene la informacion y la lista de productos de la orden"
                  required: true
                  schema:
                      $ref: "#/definitions/OrderStatusRequest"
            responses:
                "200":
                    description: "successful operation"
                "400":
                    description: "Invalid ID supplied"
                "404":
                    description: "Order not found"
definitions:
    UserResponse:
        type: "array"
        description: "Informacion del usuario"
        items:
            $ref: "#/definitions/User"
    User:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "ID del proveedor"
            type:
                type: "integer"
                format: "int64"
                enum:
                - 0
                - 1
                - 2
                default: 2
                description: "Tipo de usuario"
            name:
                type: "string"
            address:
                type: "string"
            img:
                type: "string"
    ProvidersResponse:
        type: "array"
        description: "Lista de proveedores"
        items:
            $ref: "#/definitions/Providers"
    Providers:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "ID del proveedor"
            name:
                type: "string"
            address:
                type: "string"
            img:
                type: "string"
            rating:
                type: "number"
                format: "float"
            description:
                type: "string"
    CatalogResponse:
        type: "array"
        description: "Lista de productos del proveedor"
        items:
            $ref: "#/definitions/Catalog"
    Catalog:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "ID de producto"
            category:
                type: "string"
                description: "ID de Categoria del producto"
            sku:
                type: "string"
                description: "Identificador unico del producto en el inventario del proveedor"
            description:
                type: "string"
                description: "Descripcion del producto"
            price:
                type: "number"
                format: "float"
            image:
                type: string
                format: byte
    CategoriesResponse:
        type: "array"
        description: "Lista de categorias de productos del proveedor"
        items:
            $ref: "#/definitions/Categories"
    Categories:
        type: "object"
        properties:
            category_id:
                type: "integer"
                format: "int64"
            name:
                type: "string"
                description: "Nombre de categoria del producto"
    OrderRequest:
        type: "array"
        description: "Lista de pedidos correspondientes al vendedor"
        items:
            $ref: "#/definitions/OrderFull"
    OrderResponse:
        type: "array"
        description: "Lista de pedidos correspondientes al vendedor"
        items:
            $ref: "#/definitions/Order"
    OrderListResponse:
        type: "array"
        description: "Lista de pedidos correspondientes al vendedor"
        items:
            $ref: "#/definitions/OrderList"
    OrderFull:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "ID de el pedido"
            date:
                type: string
                format: date-time
            status:
                type: "integer"
                format: "int64"
                enum:
                - 0
                - 1
                - 2
                - 3
                default: 1
                description: "Estatus de el pedido"
            total:
                type: "number"
                format: "float"
                description: "Total al que asciende el pedido"
            client_name:
                type: "string"
                description: "Nombre del cliente/negocio que realiza el pedido"
            client_id:
                type: "integer"
                format: "int64"
                description: "ID del cliente/negocio que realiza el pedido"
            client_address:
                type: "string"
                description: "Dirección del cliente/negocio que realiza el pedido"
            vendor_id:
                type: "integer"
                format: "int64"
                description: "ID del vendedor encargado del cliente/negocio que realiza el pedido"
            order_list:
                type: "array"
                items:
                    $ref: "#/definitions/OrderList"
    Order:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "ID de el pedido"
            date:
                type: string
                format: date-time
            status:
                type: "integer"
                format: "int64"
                description: "Estatus de el pedido"
            total:
                type: "number"
                format: "float"
                description: "Total al que asciende el pedido"
            client_name:
                type: "string"
                description: "Nombre del cliente/negocio que realiza el pedido"
            client_id:
                type: "integer"
                format: "int64"
                description: "ID del cliente/negocio que realiza el pedido"
            client_address:
                type: "string"
                description: "Dirección del cliente/negocio que realiza el pedido"
            vendor_id:
                type: "integer"
                format: "int64"
                description: "ID del vendedor encargado del cliente/negocio que realiza el pedido"
    OrderList:
        type: "object"
        properties:
            id:
                type: "integer"
                format: "int64"
                description: "Id del producto"
            sku:
                type: "string"
                description: "Identificador Unico del producto en el inventario del proveedor"
            description:
                type: "string"
                description: "Descripcion del producto"
            quantity:
                type: "integer"
                format: "int64"
                description: "Cantidad de unidades requeridas de el producto"
    OrderStatusRequest:
        type: "object"
        properties:
            status:
                type: "integer"
                format: "int64"
                description: "ID del status nuevo"
